### PR TITLE
bug/route matching

### PR DESCRIPTION
**Pull request by dscottboggs**
There is an issue with some of the routes being recognized and responding. I'm not sure if this is an issue with our API structure or with Kemal.

### CODE REVIEW

**Comment by dscottboggs** [comment]
To demonstrate the issue, run the attached file [`problem2.cr`](https://raw.githubusercontent.com/DFabric/dppm-rest-api/ac29b331cf8d2d9ad2a31a1bfbcb42b841f709bf/problem2.cr) from within the project directory (or any project dir with `spec-kemal` set up).

For example:

```sh
mkdir test-problem
cd $_
<< HERE >> shard.yml
name: test-problem
version: 0.0.1

dependencies:
  kemal:
    github: kemalcr/kemal
  spec-kemal:
    github: kemalcr/spec-kemal
    branch: master
HERE
shards install
wget https://raw.githubusercontent.com/DFabric/dppm-rest-api/ac29b331cf8d2d9ad2a31a1bfbcb42b841f709bf/problem2.cr
KEMAL_ENV=test crystal run problem2.cr
```
to clean up, you can then `rm -r test-problem` from the parent directory

**Comment by j8r** [comment]
I noticed that the issue only impact `PUT` calls.

**Comment by dscottboggs** [comment]
Yes, you're right...but it doesn't seem to be *all* of the PUT routes, and changing all PUT routes to patch doesn't seem to resolve it.

**Comment by j8r** [comment]
If we remove the line `{"PUT", "/dppmrestapi/actions/app/:package_name"},`, all tests pass.

**Comment by dscottboggs** [comment]
Oh wow, nice find!!


---- On Sun, 02 Jun 2019 15:39:29 -0400 notifications@github.com wrote ----



If we remove the line {"PUT", "/dppmrestapi/actions/app/:package_name"},, all tests pass.

**Comment by j8r** [comment]
Solved by renaming to `{"PUT", "/dppmrestapi/actions/app/:app_name"},`. I guess this route is for updating the application's name?
This remind me this produces a downtime, unless the system service isn't renamed too and the application supports reloading.

**Pull request closed without merging**
